<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(RunConfiguration)' == 'https' " />
  <PropertyGroup Condition=" '$(RunConfiguration)' == 'http' " />
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="7.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.20" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.20" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="7.0.12" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Contexts\" />
    <None Remove="Areas\" />
    <None Remove="Areas\Admin\" />
    <None Remove="Areas\Admin\Controllers\" />
    <None Remove="Areas\Admin\Views\" />
    <None Remove="Areas\Admin\Models\" />
    <None Remove="Areas\Admin\Views\Shared\" />
    <None Remove="Views\Auth\" />
    <None Remove="PrivateResources\" />
    <None Remove="PrivateResources\ScanFiles\" />
    <None Remove="DTOs\" />
    <None Remove="Services\" />
    <None Remove="Services\Interfaces\" />
    <None Remove="Repos\" />
    <None Remove="Repos\Interfaces\" />
    <None Remove="Areas\Admin\Views\Dashboard\" />
    <None Remove="Views\Home\" />
    <None Remove="Models\" />
    <None Remove="Configurations\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Contexts\" />
    <Folder Include="Areas\" />
    <Folder Include="Areas\Admin\" />
    <Folder Include="Areas\Admin\Controllers\" />
    <Folder Include="Areas\Admin\Views\" />
    <Folder Include="Areas\Admin\Models\" />
    <Folder Include="Areas\Admin\Views\Shared\" />
    <Folder Include="Views\Auth\" />
    <Folder Include="PrivateResources\" />
    <Folder Include="PrivateResources\ScanFiles\" />
    <Folder Include="DTOs\" />
    <Folder Include="Services\" />
    <Folder Include="Services\Interfaces\" />
    <Folder Include="Repos\" />
    <Folder Include="Repos\Interfaces\" />
    <Folder Include="Areas\Admin\Views\Dashboard\" />
    <Folder Include="Views\Home\" />
    <Folder Include="Models\" />
    <Folder Include="wwwroot\assets\img\" />
    <Folder Include="wwwroot\assets\img\defaults\" />
    <Folder Include="wwwroot\assets\img\defaults\avatars\" />
    <Folder Include="wwwroot\assets\img\defaults\icons\" />
    <Folder Include="Configurations\" />
  </ItemGroup>
  <ItemGroup>
    <Content Remove="wwwroot\assets\img\" />
    <Content Remove="wwwroot\assets\img\defaults\" />
    <Content Remove="wwwroot\assets\img\defaults\avatars\" />
    <Content Remove="wwwroot\assets\img\defaults\icons\" />
  </ItemGroup>
</Project>
